# Generated by Django 4.1.4 on 2023-01-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_trimester', models.IntegerField()),
                ('second_trimester', models.IntegerField()),
                ('third_trimester', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
