# Generated by Django 4.1.4 on 2023-01-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_subject_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
    ]
