# Generated by Django 4.1.4 on 2023-01-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_note_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
