# Generated by Django 4.1.4 on 2023-01-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_subject_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentsGroup',
        ),
    ]
