# Generated by Django 4.1.4 on 2023-01-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_rename_group_studentsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
    ]
