# Generated by Django 4.1.4 on 2023-01-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_note_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='first_trimester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='second_trimester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
        migrations.AlterField(
            model_name='note',
            name='third_trimester',
            field=models.IntegerField(null=True),
        ),
    ]
