# Generated by Django 4.1.4 on 2023-01-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_note_first_trimester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='first_trimester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='second_trimester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='third_trimester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
