# Generated by Django 4.1.4 on 2023-01-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='first_trimester',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='note',
            name='second_trimester',
        ),
        migrations.RemoveField(
            model_name='note',
            name='third_trimester',
        ),
    ]
